### ISSUE TITLE
repo needs to be renamed

### ISSUE THREAD

**Issue by rimusz** [helm/charts-classic#100]
googling for `helm charts` this repo comes as a second option from the top.
Craig Box from google asked to rename this repo.

**Comment by mboersma** [comment]
@rimusz what would clarify things best? Ideas:

- helm/old-charts
- helm/classic-charts
- helm/obsolete-charts
- helm/charts-classic

Or do we need to archive it completely or move it to deis/classic-charts?

**Comment by rimusz** [comment]
we could rename it to `helm/classic-charts` so that is in line with `helm/helm-classic', maybe we could put a note that repos `helm/classic-charts` and `helm/helm-classic' will be archived by end of June?

**Comment by bacongobbler** [comment]
helm/charts-classic sounds good to me.

**Comment by rimusz** [comment]
shall I do the honours then?

**Comment by bacongobbler** [comment]
done.

**Comment by mboersma** [comment]
This repo still shows up in GitHub search for "helm charts", but further down in the list. I changed the repo description to start with `(OBSOLETE)`, updated the repo URL to point to kubernetes/charts, and I'll create some README PRs to include a deprecation notice. That should do for now, and then we can decide whether archival is necessary soon (everyone's in Germany or traveling back from Kubecon today, so no rush).
